# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 11:50
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Published', max_length=100, no_check_for_status=True),
        ),
    ]
