# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:08
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170615_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_date',
        ),
        migrations.AddField(
            model_name='article',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
