# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170615_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='coauthors',
            field=models.ManyToManyField(blank=True, related_name='articles_coauthored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
