# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170615_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(blank=True, to='blog.Label'),
        ),
    ]
