# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170615_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Label'),
        ),
    ]
