# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170615_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status_changed',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='_body_excerpt',
            field=models.TextField(default='empty', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=model_utils.fields.SplitField(default='empty', no_excerpt_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when=set(['Published'])),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Draft', max_length=100, no_check_for_status=True),
        ),
    ]
