# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170619_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='splash_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
