# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_splash_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='splash_image',
            new_name='featured_image',
        ),
    ]
