# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('category', models.CharField(choices=[('Instructional Design', 'Instructional Design'), ('Sales', 'Sales')], default='Instructional Design', max_length=30)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
